# Generated by Django 4.2.2 on 2023-07-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=70)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categorie')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(auto_created=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store')),
                ('precio', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
            },
        ),
    ]
