# Generated by Django 4.2.2 on 2023-07-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_pub_created_pub_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
