# Generated by Django 4.2.2 on 2023-07-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub',
            old_name='precio',
            new_name='price',
        ),
    ]
