# Generated by Django 4.2.2 on 2023-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiciosBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='try_it_numb',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='image',
            field=models.ImageField(upload_to='ServiciosBot'),
        ),
    ]
