# Generated by Django 4.2.2 on 2023-07-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=254, verbose_name='Mail')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('estatus', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('wap_id', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=15)),
                ('mime_type', models.CharField(max_length=70)),
                ('sha256', models.CharField(max_length=70)),
                ('media_id', models.CharField(max_length=30)),
            ],
        ),
    ]
